### ISSUE TITLE
what does this "Market2Duke" and  "Duke2Market" mean

### ISSUE THREAD

**Issue by prajotsl123** [NVlabs/DG-Net-PP#1]
i have a huge confusion...on these 2 terms
Can you give an explanation on what do you mean by  "Market2Duke" and  "Duke2Market"....?

**Comment by yzou2** [comment]
"Market2Duke" means adapting model from "Market-1501 to DukeMTMC-reID". Similar definition can be defined for "Duke2Market"

**Comment by prajotsl123** [comment]
> "Market2Duke" means adapting model from "Market-1501 to DukeMTMC-reID". Similar definition can be defined for "Duke2Market"

Means first training on Market dataset and training the same model on Duke?

**Comment by yzou2** [comment]
It's the standard unsupervised domain adaptation setting. Market2duke means training with labeled Market first then train with labeled Duke to adapt model.
